name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate SVG
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: yoshi389111/github-contribution-graph-action@main
        with:
          mode: pacman
          output_dir: ./output
          dark: true

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/*
          git commit -m "update pacman graph" || echo "No changes to commit"
          git push
